### ISSUE TITLE
error: 'std::size_t' has not been declared

### ISSUE THREAD

**Issue by jputcu** [ETLCPP/etl#427]
After upgrading from 20.9.3 to 20.17.1 I get compilation errors in 'utility.h' on my AVR platform.

```
etl/utility.h:429:13: error: 'std::size_t' has not been declared
   template <std::size_t I> struct in_place_index_t
```

**Comment by jwellbelove** [comment]
Fixe in 20.17.2
