### ISSUE TITLE
Compilation errors on basic_string

### ISSUE THREAD

**Issue by jputcu** [ETLCPP/etl#1181]
After upgrading to 20.43.0 I got following errors with avr-gcc-7.3:

- include/etl/basic_string.h:54:12: fatal error: wchar.h: No such file or directory
    -> fixed using "-DETL_NO_LIBC_WCHAR_H"
- include/etl/basic_string.h:62:12: fatal error: ostream: No such file or directory

This last one is a bit harder to fix, it is surrounded by "ETL_USING_STL" which I activated because I use avr-libstdcpp (https://github.com/modm-io/avr-libstdcpp)

I use C++17, would it be possible to using `__has_include` checks instead?

**Comment by mike919192** [comment]
That ostream include is my fault.  I guess the `ETL_USING_STL` macro is not enough protection for it.

`__has_include` being C++17 would preclude its use for older versions.  I think we would need another profile macro to enable the use of ostream, probably defaulted to off.  The convention for other features is something like `ETL_HAS_STD_OSTREAM`.

**Comment by jputcu** [comment]
I've found examples of first checking for existence of `__has_include` and then using it.
Using this feature would hopefully avoid some defines (e.g. `ETL_NO_LIBC_WCHAR_H`) and make the configuration more plug&play and less error prone on newer compilers (GCC-5 already implemented this feature)

**Comment by jwellbelove** [comment]
Can you try this patch?

[etl-#1181-1-Compilation errors on basic_string.patch](https://github.com/user-attachments/files/22187539/etl-.1181-1-Compilation.errors.on.basic_string.patch)

**Comment by jputcu** [comment]
I get the following error after applying the patch:
~~~~
include/etl/basic_string.h:3132:8: error: 'basic_ostream' in namespace 'std' does not name a template type
   std::basic_ostream<T, std::char_traits<T> > &operator<<(std::basic_ostream<T, std::char_traits<T> > &os,
~~~~

**Comment by jputcu** [comment]
It appears these locations still used the `ETL_USING_STL`:
* string_view.h:985
* basic_string:3130

**Comment by jputcu** [comment]
Changing those locations to use the `ETL_USING_STD_OSTREAM` define fixes the compilation errors.

Still one small warning:
~~~~
include/etl/private/vector_base.h:171:28: warning: extra ';' [-Wpedantic]
     ETL_DECLARE_DEBUG_COUNT;   ///< Internal debugging.
~~~~

**Comment by mike919192** [comment]
@jwellbelove This was the PR #1040 so you can review the diff.

As @jputcu points out, there are uses where `#if ETL_USING_STL` should be changed to `#if ETL_USING_STD_OSTREAM` in basic_string.h and string_view.h.  There are also tests that were added that could also be updated to use the new macro.

**Comment by jwellbelove** [comment]
> include/etl/private/vector_base.h:171:28: warning: extra ';' [-Wpedantic]
>      ETL_DECLARE_DEBUG_COUNT;   ///< Internal debugging.

That must be in a 'no debug' compilation.
I would need to tweak the ETL_XXX_DEBUG_COUNT definitions.

**Comment by jwellbelove** [comment]
Fixed 20.43.1
