### ISSUE TITLE
error: no template named 'tuple_size'

### ISSUE THREAD

**Issue by vagran** [ETLCPP/etl#1404]
Trying to compile with Clang 22.1.1 ETL 20.47.1 with `ETL_NO_STL`:
```
In file included from src/app/main.cpp:2:
In file included from modules/etl/include/etl/atomic.h:44:
In file included from modules/etl/include/etl/atomic/atomic_clang_sync.h:32:
In file included from modules/etl/include/etl/atomic/atomic_gcc_sync.h:33:
In file included from modules/etl/include/etl/atomic/../char_traits.h:35:
In file included from modules/etl/include/etl/atomic/../algorithm.h:50:
In file included from modules/etl/include/etl/atomic/../ranges.h:40:
modules/etl/include/etl/atomic/../tuple.h:1198:10: error: no template named 'tuple_size'; did you mean 'etl::tuple_size'?
 1198 |   struct tuple_size<etl::tuple<Types...>> : etl::integral_constant<size_t, sizeof...(Types)>
      |          ^
modules/etl/include/etl/private/tuple_size.h:38:10: note: 'etl::tuple_size' declared here
   38 |   struct tuple_size;
      |          ^
In file included from src/app/main.cpp:2:
In file included from modules/etl/include/etl/atomic.h:44:
In file included from modules/etl/include/etl/atomic/atomic_clang_sync.h:32:
In file included from modules/etl/include/etl/atomic/atomic_gcc_sync.h:33:
In file included from modules/etl/include/etl/atomic/../char_traits.h:35:
In file included from modules/etl/include/etl/atomic/../algorithm.h:50:
In file included from modules/etl/include/etl/atomic/../ranges.h:40:
modules/etl/include/etl/atomic/../tuple.h:1198:10: error: class template partial specialization of 'tuple_size' not in a namespace enclosing 'etl'
 1198 |   struct tuple_size<etl::tuple<Types...>> : etl::integral_constant<size_t, sizeof...(Types)>
      |          ^
modules/etl/include/etl/private/tuple_size.h:38:10: note: explicitly specialized declaration is here
   38 |   struct tuple_size;
      |          ^
In file included from src/app/main.cpp:2:
In file included from modules/etl/include/etl/atomic.h:44:
In file included from modules/etl/include/etl/atomic/atomic_clang_sync.h:32:
In file included from modules/etl/include/etl/atomic/atomic_gcc_sync.h:33:
In file included from modules/etl/include/etl/atomic/../char_traits.h:35:
In file included from modules/etl/include/etl/atomic/../algorithm.h:50:
In file included from modules/etl/include/etl/atomic/../ranges.h:40:
modules/etl/include/etl/atomic/../tuple.h:1198:10: error: redefinition of 'tuple_size<etl::tuple<Types...>>'
 1198 |   struct tuple_size<etl::tuple<Types...>> : etl::integral_constant<size_t, sizeof...(Types)>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
modules/etl/include/etl/atomic/../tuple.h:719:10: note: previous definition is here
  719 |   struct tuple_size<etl::tuple<TTypes...>> : etl::integral_constant<size_t, sizeof...(TTypes)>
      |          ^
modules/etl/include/etl/atomic/../tuple.h:1207:10: error: no template named 'tuple_element'; did you mean 'etl::tuple_element'?
 1207 |   struct tuple_element<Index, etl::tuple<Types...>>
      |          ^
modules/etl/include/etl/private/tuple_element.h:39:10: note: 'etl::tuple_element' declared here
   39 |   struct tuple_element;
      |          ^
In file included from src/app/main.cpp:2:
In file included from modules/etl/include/etl/atomic.h:44:
In file included from modules/etl/include/etl/atomic/atomic_clang_sync.h:32:
In file included from modules/etl/include/etl/atomic/atomic_gcc_sync.h:33:
In file included from modules/etl/include/etl/atomic/../char_traits.h:35:
In file included from modules/etl/include/etl/atomic/../algorithm.h:50:
In file included from modules/etl/include/etl/atomic/../ranges.h:40:
modules/etl/include/etl/atomic/../tuple.h:1207:10: error: class template partial specialization of 'tuple_element' not in a namespace enclosing 'etl'
 1207 |   struct tuple_element<Index, etl::tuple<Types...>>
      |          ^
modules/etl/include/etl/private/tuple_element.h:39:10: note: explicitly specialized declaration is here
   39 |   struct tuple_element;
      |          ^
In file included from src/app/main.cpp:2:
In file included from modules/etl/include/etl/atomic.h:44:
In file included from modules/etl/include/etl/atomic/atomic_clang_sync.h:32:
In file included from modules/etl/include/etl/atomic/atomic_gcc_sync.h:33:
In file included from modules/etl/include/etl/atomic/../char_traits.h:35:
In file included from modules/etl/include/etl/atomic/../algorithm.h:50:
In file included from modules/etl/include/etl/atomic/../ranges.h:40:
modules/etl/include/etl/atomic/../tuple.h:1207:10: error: redefinition of 'tuple_element<Index, etl::tuple<Types...>>'
 1207 |   struct tuple_element<Index, etl::tuple<Types...>>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
modules/etl/include/etl/atomic/../tuple.h:710:10: note: previous definition is here
  710 |   struct tuple_element<Index, etl::tuple<TTypes...>>
      |          ^
6 errors generated.
```
This looks like some regression, it works with ETL 20.45.0.

Toolchain file:
```
set(CMAKE_SYSTEM_NAME Generic-ELF)
set(CMAKE_SYSTEM_PROCESSOR ARM)

set(TOOLCHAIN_TRIPLE arm-none-eabi)
find_program(CLANG_PATH clang NO_CACHE)

if (NOT CLANG_PATH)
    message(FATAL_ERROR "Clang toolchain not found")
endif ()

find_program(CLANGPP_PATH clang++ NO_CACHE)

get_filename_component(ARM_TOOLCHAIN_DIR ${CLANG_PATH} DIRECTORY)
# Without that flag CMake is not able to pass test compilation check
if (${CMAKE_VERSION} VERSION_EQUAL "3.6.0" OR ${CMAKE_VERSION} VERSION_GREATER "3.6")
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
else ()
    set(CMAKE_EXE_LINKER_FLAGS_INIT "--specs=nosys.specs")
endif ()

set(CMAKE_C_COMPILER ${CLANG_PATH})
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})
set(CMAKE_CXX_COMPILER ${CLANGPP_PATH})
set(CMAKE_C++_LINK_EXECUTABLE ${CLANGPP_PATH})
set(CMAKE_AR ${ARM_TOOLCHAIN_DIR}/llvm-ar)
set(CMAKE_RANLIB ${ARM_TOOLCHAIN_DIR}/llvm-ranlib)

# Clang target flag
set(CLANG_TARGET_FLAG "--target=${TOOLCHAIN_TRIPLE}")

# Default C compiler flags
set(CMAKE_C_FLAGS_INIT "${CLANG_TARGET_FLAG} -ffreestanding -nostdlib -fno-builtin")
set(CMAKE_C_FLAGS_DEBUG_INIT "-g3 -Og")
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG_INIT}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE_INIT "-O3")
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE_INIT}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_MINSIZEREL_INIT "-Oz")
set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL_INIT}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO_INIT}" CACHE STRING "" FORCE)

# Default C++ compiler flags
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} -fno-exceptions -fno-unwind-tables -fno-rtti")
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-g3 -Og")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG_INIT}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O3")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE_INIT}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT "-Oz")
set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL_INIT}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT}" CACHE STRING "" FORCE)

set(CMAKE_ASM_FLAGS_INIT "${CLANG_TARGET_FLAG}")

set(CMAKE_EXE_LINKER_FLAGS_INIT "${CLANG_TARGET_FLAG} -nostartfiles -fuse-ld=lld --sysroot=${CMAKE_SYSROOT} -L${CMAKE_SYSROOT}/lib/thumb/v7-m/nofp -lc -lm")

set(CMAKE_OBJCOPY ${ARM_TOOLCHAIN_DIR}/llvm-objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${ARM_TOOLCHAIN_DIR}/llvm-size CACHE INTERNAL "size tool")

set(CMAKE_SYSROOT /usr/arm-none-eabi)
set(CMAKE_FIND_ROOT_PATH ${CLANG_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

**Comment by rolandreichweinbmw** [comment]
Can you confirm if the change in https://github.com/ETLCPP/etl/pull/1407 fixes the issue for you?

**Comment by vagran** [comment]
> Can you confirm if the change in [#1407](https://github.com/ETLCPP/etl/pull/1407) fixes the issue for you?

Tried it, and now it fails with including `<utility>` header. As mentioned in the issue, I do not have STL and have `ETL_NO_STL` defined.
```
In file included from etl/include/etl/atomic.h:44:
In file included from etl/include/etl/atomic/atomic_clang_sync.h:32:
In file included from etl/include/etl/atomic/atomic_gcc_sync.h:33:
In file included from etl/include/etl/atomic/../char_traits.h:35:
In file included from etl/include/etl/atomic/../algorithm.h:50:
In file included from etl/include/etl/atomic/../ranges.h:40:
etl/include/etl/atomic/../tuple.h:1193:14: fatal error: 'utility' file not found
 1193 |     #include <utility>
      |              ^~~~~~~~~
1 error generated.
```

**Comment by rolandreichweinbmw** [comment]
Yes, of course. Thank you for the note!

I just updated it. Can you please re-try?

**Comment by vagran** [comment]
Looks now it has the original error:
```
In file included from etl/include/etl/atomic.h:44:
In file included from etl/include/etl/atomic/atomic_clang_sync.h:32:
In file included from etl/include/etl/atomic/atomic_gcc_sync.h:33:
In file included from etl/include/etl/atomic/../char_traits.h:35:
In file included from etl/include/etl/atomic/../algorithm.h:50:
In file included from etl/include/etl/atomic/../ranges.h:40:
etl/include/etl/atomic/../tuple.h:1223:10: error: no template named 'tuple_size'; did you mean 'etl::tuple_size'?
 1223 |   struct tuple_size<etl::tuple<Types...>> : etl::integral_constant<size_t, sizeof...(Types)>
      |          ^
etl/include/etl/private/tuple_size.h:38:10: note: 'etl::tuple_size' declared here
   38 |   struct tuple_size;
      |          ^
In file included from etl/include/etl/atomic.h:44:
In file included from etl/include/etl/atomic/atomic_clang_sync.h:32:
In file included from etl/include/etl/atomic/atomic_gcc_sync.h:33:
In file included from etl/include/etl/atomic/../char_traits.h:35:
In file included from etl/include/etl/atomic/../algorithm.h:50:
In file included from etl/include/etl/atomic/../ranges.h:40:
etl/include/etl/atomic/../tuple.h:1223:10: error: class template partial specialization of 'tuple_size' not in a namespace enclosing 'etl'
 1223 |   struct tuple_size<etl::tuple<Types...>> : etl::integral_constant<size_t, sizeof...(Types)>
      |          ^
etl/include/etl/private/tuple_size.h:38:10: note: explicitly specialized declaration is here
   38 |   struct tuple_size;
      |          ^
In file included from etl/include/etl/atomic.h:44:
In file included from etl/include/etl/atomic/atomic_clang_sync.h:32:
In file included from etl/include/etl/atomic/atomic_gcc_sync.h:33:
In file included from etl/include/etl/atomic/../char_traits.h:35:
In file included from etl/include/etl/atomic/../algorithm.h:50:
In file included from etl/include/etl/atomic/../ranges.h:40:
etl/include/etl/atomic/../tuple.h:1223:10: error: redefinition of 'tuple_size<etl::tuple<Types...>>'
 1223 |   struct tuple_size<etl::tuple<Types...>> : etl::integral_constant<size_t, sizeof...(Types)>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
etl/include/etl/atomic/../tuple.h:724:10: note: previous definition is here
  724 |   struct tuple_size<etl::tuple<TTypes...>> : etl::integral_constant<size_t, sizeof...(TTypes)>
      |          ^
etl/include/etl/atomic/../tuple.h:1232:10: error: no template named 'tuple_element'; did you mean 'etl::tuple_element'?
 1232 |   struct tuple_element<Index, etl::tuple<Types...>>
      |          ^
etl/include/etl/private/tuple_element.h:39:10: note: 'etl::tuple_element' declared here
   39 |   struct tuple_element;
      |          ^
In file included from etl/include/etl/atomic.h:44:
In file included from etl/include/etl/atomic/atomic_clang_sync.h:32:
In file included from etl/include/etl/atomic/atomic_gcc_sync.h:33:
In file included from etl/include/etl/atomic/../char_traits.h:35:
In file included from etl/include/etl/atomic/../algorithm.h:50:
In file included from etl/include/etl/atomic/../ranges.h:40:
etl/include/etl/atomic/../tuple.h:1232:10: error: class template partial specialization of 'tuple_element' not in a namespace enclosing 'etl'
 1232 |   struct tuple_element<Index, etl::tuple<Types...>>
      |          ^
etl/include/etl/private/tuple_element.h:39:10: note: explicitly specialized declaration is here
   39 |   struct tuple_element;
      |          ^
In file included from etl/include/etl/atomic.h:44:
In file included from etl/include/etl/atomic/atomic_clang_sync.h:32:
In file included from etl/include/etl/atomic/atomic_gcc_sync.h:33:
In file included from etl/include/etl/atomic/../char_traits.h:35:
In file included from etl/include/etl/atomic/../algorithm.h:50:
In file included from etl/include/etl/atomic/../ranges.h:40:
etl/include/etl/atomic/../tuple.h:1232:10: error: redefinition of 'tuple_element<Index, etl::tuple<Types...>>'
 1232 |   struct tuple_element<Index, etl::tuple<Types...>>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
etl/include/etl/atomic/../tuple.h:715:10: note: previous definition is here
  715 |   struct tuple_element<Index, etl::tuple<TTypes...>>
      |          ^
```

**Comment by rolandreichweinbmw** [comment]
Unfortunately, doesn't happen in my environment with clang 22.1.3:

`main.cpp`
```
#include "etl/atomic.h"

int main()
{
        return 0;
}
```

Compile with:
```
clang++ -std=c++23 -I ../include -Wall -DETL_COMPILER_CLANG -DETL_NO_STL main.cpp -o main
```

What would I need to change here to reproduce your use case?

**Comment by vagran** [comment]
It should have an embedded target without a standard library, as described in the toolchain file.

I reproduced it with your `main.cpp` and the following command:
```
clang++ -I ../include -DETL_NO_STL --target=arm-none-eabi -ffreestanding -nostdlib -fno-builtin -std=c++23 -mcpu=cortex-m3 -mthumb -ffunction-sections -fdata-sections -fno-common -o main.o -c main.cpp
```

Also as I understand, you do not need to specify `-DETL_COMPILER_CLANG`, it should be automatically detected.

**Comment by rolandreichweinbmw** [comment]
For reproducability, can you give me a link to this clang binary toolchain?

**Comment by vagran** [comment]
Toolchain file content is in the issue description (attached same file). I use Clang 22.1.1 installed from official package on Arch Linux.

[arm-clang-toolchain.zip](https://github.com/user-attachments/files/27052466/arm-clang-toolchain.zip)

**Comment by vagran** [comment]
Were you able to reproduce it using the command in my previous message?

**Comment by rolandreichweinbmw** [comment]
I couldn't reproduce yet, but thanks for the hint with Archlinux!

I did like this:

Using this Dockerfile:
```
FROM amd64/archlinux:latest

RUN pacman -Syu --noconfirm && pacman -S --noconfirm \
    base-devel \
    cmake \
    git \
    ninja \
    python \
    python-cogapp \
    clang \
    libc++ \
    lld \
    && pacman -Scc --noconfirm

RUN useradd -m -s /bin/bash archlinux

WORKDIR /etl

CMD ["/bin/bash"]
```

And running:
```
clang++ -I ../include -DETL_NO_STL --target=arm-none-eabi -ffreestanding -nostdlib -fno-builtin -std=c++23 -mcpu=cortex-m3 -mthumb -ffunction-sections -fdata-sections -fno-common -o main.o -c main.cpp
```

I get:

```
In file included from main.cpp:1:
In file included from ../include/etl/atomic.h:32:
In file included from ../include/etl/platform.h:49:
In file included from /usr/bin/../include/c++/v1/stddef.h:30:
/usr/bin/../include/c++/v1/__config:646:8: error: "No thread API"
  646 | #      error "No thread API"
      |        ^
In file included from main.cpp:1:
In file included from ../include/etl/atomic.h:44:
In file included from ../include/etl/atomic/atomic_clang_sync.h:32:
In file included from ../include/etl/atomic/atomic_gcc_sync.h:33:
In file included from ../include/etl/atomic/../char_traits.h:35:
In file included from ../include/etl/atomic/../algorithm.h:42:
../include/etl/atomic/../error_handler.h:44:10: fatal error: 'assert.h' file not found
   44 | #include <assert.h>
      |          ^~~~~~~~~~
2 errors generated.
```

Do I need to install more into this environment?

**Comment by rolandreichweinbmw** [comment]
Update: I could partially reproduce the original issue by including ranges.h directly. Still getting the above other error.

The original error goes away for me with the updated PR's branch. Special casing for clang 22 now.

**Comment by vagran** [comment]
May be try also installing `arm-none-eabi-gcc` package, I believe clang uses sysroot it installs if present.

**Comment by vagran** [comment]
> Update: I could partially reproduce the original issue by including ranges.h directly. Still getting the above other error.
> 
> The original error goes away for me with the updated PR's branch. Special casing for clang 22 now.

Checked latest PR branch, error is fixed for me now.

**Comment by Leandros** [comment]
I'm getting the same error with the embedded arm clang toolchain.

**Comment by rolandreichweinbmw** [comment]
> I'm getting the same error with the embedded arm clang toolchain.

Can you check if the branch from #1407 fixes it for you? It is also merged into the development branch which you could test alternatively.

@vagran already confirmed it did the job for him.

**Comment by Leandros** [comment]
@rolandreichweinbmw , yes, the fix on the `development` branch works. Thank you!

**Comment by jwellbelove** [comment]
Fixed 20.48.0
