### ISSUE TITLE
zero-length vector doesn't compile

### ISSUE THREAD

**Issue by Michaelhobo** [ETLCPP/etl#260]
This may seem silly, but I have a class that contains a few vectors for tracking various things (e.g. buffer sizes for events), and sometimes the vector is 0-sized if we don't expect anything in the container for a specific use case.

This happens when I create an etl::vector<T, 0> using the default constructor. When I bump it up to 1, it works.

```
In file included from ../../s_test.cpp:1:
s.h: In instantiation of 'scheduler::Impl<MaxEvents, MaxTimers>::Impl(nrf::RTC*) [with long unsigned int MaxEvents = 5; long unsigned int MaxTimers = 0]':
s_test.cpp:72:62:   required from here
s.h:122:66: error: no matching function for call to 'etl::vector<scheduler::Timer, 0>::vector(<brace-enclosed initializer list>)'
  122 |   Impl(nrf::RTC* rtc) : rtc_(rtc), timers_({}), last_rtc_ticks_(0) {}
      |                                                                  ^
In file included from s.h:13,
                 from s_test.cpp:1:
../../etl/include/etl/vector.h:1382:5: note: candidate: 'etl::vector<T, 0>::vector(etl::vector<T, 0>&&, void*, size_t) [with T = scheduler::Timer; size_t = long unsigned int]'
 1382 |     vector(vector&& other, void* buffer, size_t max_size)
      |     ^~~~~~
../../etl/include/etl/vector.h:1382:5: note:   candidate expects 3 arguments, 1 provided
../../etl/include/etl/vector.h:1359:5: note: candidate: 'etl::vector<T, 0>::vector(const etl::vector<T, 0>&, void*, size_t) [with T = scheduler::Timer; size_t = long unsigned int]'
 1359 |     vector(const vector& other, void* buffer, size_t max_size)
      |     ^~~~~~
../../etl/include/etl/vector.h:1359:5: note:   candidate expects 3 arguments, 1 provided
../../etl/include/etl/vector.h:1349:5: note: candidate: 'etl::vector<T, 0>::vector(std::initializer_list<_Tp>, void*, size_t) [with T = scheduler::Timer; size_t = long unsigned int]'
 1349 |     vector(std::initializer_list<T> init, void* buffer, size_t max_size)
      |     ^~~~~~
../../etl/include/etl/vector.h:1349:5: note:   candidate expects 3 arguments, 1 provided
../../etl/include/etl/vector.h:1339:5: note: candidate: 'template<class TIterator> etl::vector<T, 0>::vector(TIterator, TIterator, void*, size_t) [with TIterator = TIterator; T = scheduler::Timer]'
 1339 |     vector(TIterator first, TIterator last, void* buffer, size_t max_size)
      |     ^~~~~~
../../etl/include/etl/vector.h:1339:5: note:   template argument deduction/substitution failed:
In file included from s_test.cpp:1:
s.h:122:66: note:   candidate expects 4 arguments, 1 provided
  122 |   Impl(nrf::RTC* rtc) : rtc_(rtc), timers_({}), last_rtc_ticks_(0) {}
      |                                                                  ^
In file included from s.h:13,
                 from s_test.cpp:1:
../../etl/include/etl/vector.h:1325:5: note: candidate: 'etl::vector<T, 0>::vector(size_t, typename etl::ivector<T>::parameter_t, void*, size_t) [with T = scheduler::Timer; size_t = long unsigned int; typename etl::ivector<T>::parameter_t = const scheduler::Timer&]'
 1325 |     vector(size_t initial_size, typename etl::ivector<T>::parameter_t value, void* buffer, size_t max_size)
      |     ^~~~~~
../../etl/include/etl/vector.h:1325:5: note:   candidate expects 4 arguments, 1 provided
../../etl/include/etl/vector.h:1313:14: note: candidate: 'etl::vector<T, 0>::vector(size_t, void*, size_t) [with T = scheduler::Timer; size_t = long unsigned int]'
 1313 |     explicit vector(size_t initial_size, void* buffer, size_t max_size)
      |              ^~~~~~
../../etl/include/etl/vector.h:1313:14: note:   candidate expects 3 arguments, 1 provided
../../etl/include/etl/vector.h:1303:5: note: candidate: 'etl::vector<T, 0>::vector(void*, size_t) [with T = scheduler::Timer; size_t = long unsigned int]'
 1303 |     vector(void* buffer, size_t max_size)
      |     ^~~~~~
../../etl/include/etl/vector.h:1303:5: note:   candidate expects 2 arguments, 1 provided
```

**Comment by Michaelhobo** [comment]
Rather than overloading 0 for this, would it be better to use something similar to std::dynamic_extent, which is basically std::numeric_limits<size_t>? I think it's clearer from a documentation perspective. I think there are valid use cases of 0, but std::numeric_limits<size_t> is rare, and usually std::numeric_limits<size_t> - 1 work just as well for such cases.

**Comment by Michaelhobo** [comment]
If this isn't possible due to it being a breaking change, I'm fine with either the workaround you mentioned, or just setting size to 1.

**Comment by jwellbelove** [comment]
To modify it now would be a breaking change.
To be honest, I never imagined that anyone would ever **_want_** a container that couldn't actually store **_any_** items.
I seemed to be like trying to define a zero sized array.

**Comment by jwellbelove** [comment]
One issue I can see with a zero capacity vector, will be that it will have the paradoxical property of being both empty and full at the same time!

**Comment by Michaelhobo** [comment]
Hm, having both empty and full being true is odd... I can see a few bugs
cropping up there.
My use case with a zero-length array is a library, where the caller
initializes how many timers they need, but having timers isn't the
library's only functionality, so it's perfectly fine to initialize the
library with 0. But, having a minimum of 1 timer isn't the end of the world
as a workaround.

**Comment by jwellbelove** [comment]
If you stick to the rule that you never access items in an empty vector and never push_back for a full vector, then I think everything should be fine.

**Comment by Michaelhobo** [comment]
Thanks for the discussion and workarounds, I don't think there's anything actionable here, so I'm closing it.

**Comment by Michaelhobo** [comment]
This is a really nice set of libraries, by the way! Aside from this small gotcha, I'm so far enjoying integrating this into my work, it's making certain problems a lot easier! Especially the icontainers. I spent a long time trying different things to get functions to accept fixed sized containers of varying sizes like std::array and sstl::vector. This solves it neatly.
